# print("hello world")
# print("Hello again")
# print("I like typing this.")
# print("printing is fun")
# print("yay printing")
# print("I much rather you 'not'")
# print('I "said" do not touch that')
print('Another line')
